Update: Ensure nonzero exit after sort-and-sign if rebase-todo exists
- This happens if you, e.g., inject "break" into the rebase-todo.

  But under normal working condition, rebase-todo will only exist
  if there's a conflict, in which case git-rebase exists nonzero.

diff --git a/bin/git-rebase-sort-by-scope-protected-private b/bin/git-rebase-sort-by-scope-protected-private
--- a/bin/git-rebase-sort-by-scope-protected-private
+++ b/bin/git-rebase-sort-by-scope-protected-private
@@ -136,10 +136,11 @@ git-rebase-sort-by-scope-protected-private () {
   seq_editor_cleanup_rebase_files
 
   print_hint_if_rebase_incomplete_or_new_state_suspicious \
-    "${head_sha_before_rebase}" "${rev_count_before_rebase}" "${retcode}"
+    "${head_sha_before_rebase}" "${rev_count_before_rebase}" "${retcode}" \
+    || retcode=$?
 
   # Always run optional user hook (GIT_POST_REBASE_EXEC) and also pop WIP...
-  if [ ${retcode} -ne 0 ] && [ -f "${GIT_REBASE_TODO_PATH}" ]; then
+  if [ -f "${GIT_REBASE_TODO_PATH}" ]; then
     # ... after rebase finishes (by appending exec to git-rebase-todo).
     git_post_rebase_exec_inject ${pop_after}
 
@@ -309,6 +310,17 @@ git_prepare_push_resort_scoped_and_sign_commits () {
     >&2 echo "ERROR: \`git rebase\` failed (${retcode}):"
     >&2 echo
     echo "${errs}" | >&2 sed 's/^/  /'
+    if [ ${retcode} -eq 0 ]; then
+
+      retcode=1
+    fi
+  elif [ -f "${GIT_REBASE_TODO_PATH}" ]; then
+    # SAVVY: This might happen if you put a "break" in the rebase-todo.
+    >&2 echo
+    >&2 echo "ERROR: \`git rebase\` stopped. Please investigate!"
+    >&2 echo
+
+    retcode=1
   else
     if [ -n "${progress_orig_msg}" ]; then
       local one_line_up="\033[1A"
@@ -326,17 +338,13 @@ git_prepare_push_resort_scoped_and_sign_commits () {
 print_hint_if_rebase_incomplete_or_new_state_suspicious () {
   local head_sha_before_rebase="$1"
   local rev_count_before_rebase="$2"
-  local retcode="$3"
+  local sort_and_sign_retcode="$3"
 
-  if [ -f "${GIT_REBASE_TODO_PATH}" ]; then
-    # git-rebase exited 1.
+  if [ ${sort_and_sign_retcode} -ne 0 ] || [ -f "${GIT_REBASE_TODO_PATH}" ]; then
     echo
     echo "Looks like you got work to do!"
-    # git-rebase exited nonzero. If not, our code is wrong.
-    if [ ${retcode} -eq 0 ]; then
-      echo
-      echo "ERROR: rebase-todo found, but git-rebase exited zero"
-    fi
+
+    return 1
   else
     local unexpected_changes_detected=false
 
@@ -364,17 +372,12 @@ print_hint_if_rebase_incomplete_or_new_state_suspicious () {
       >&2 echo "- Try:"
       >&2 echo
       >&2 echo "    git diff ${head_sha_before_rebase}..HEAD"
-    fi
 
-    # git-rebase exited zero. If not, our code is wrong.
-    # - Or I (lb) assume it is. Obviously, git-rebase can fail for other,
-    #   non-conflict reasons (e.g., bad args), but I assume the way the
-    #   code works that it won't.
-    if [ ${retcode} -ne 0 ]; then
-      echo
-      echo "ERROR: rebase-todo not found, but git-rebase exited nonzero"
+      return 1
     fi
   fi
+
+  return 0
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
